# _config.yml
title: "Мои чудесные маленькие друзья"
description: "Личный сайт фотографа Алексея Трубина"
baseurl: ""   # если сайт в корне репозитория, оставь пустым
url: "https://твой-логин.github.io"  # подставь свой адрес
lang: ru      # язык по умолчанию

# Для поддержки мультиязычности можно добавить
languages: ["ru", "en"]
default_lang: "ru"